---
# handlers file for ghobadimhd.postfix

- name: postmap virtual mailbox map
  command: "postmap {{ virtual_mailbox_maps }}"

- name: postmap virtual uid map
  command: "postmap {{ virtual_mailbox_uid_maps }}"

- name: postmap virtual gid map
  command: "postmap {{ virtual_mailbox_gid_maps }}"

- name: postmap virtual domains
  command: "postmap {{ vdomains_map_type }}:/etc/postfix/virtual_domains_maps"
  when: vdomains_map_type == 'hash' and vdomains_enable

- name: restart saslauthd
  service:
    name: saslauthd
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: postfix reload
  service:
    name: postfix
    state: reloaded